version: '3.7'

services:
  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    container_name: php_app
    volumes:
      - ../main:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ../main:/var/www/html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
